// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zozkkcsecoroingrakqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvemtrY3NlY29yb2luZ3Jha3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDcwNzMsImV4cCI6MjA3MTk4MzA3M30.835Q5DTD0GrCZExNXm81Kyatg4zMBUQ0YPBjcZl2vXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});